apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin:latest
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
        resources:
         limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
